<?php
/**
 * SB Mobile Shop - Installation Script
 * Run this file to install the script on your cPanel hosting
 */

define('INSTALLING', true);

$step = $_GET['step'] ?? 1;
$errors = [];
$success = false;

// Check requirements
$phpVersion = phpversion();
$requirementsMet = version_compare($phpVersion, '7.4.0', '>=');
$pdoExtension = extension_loaded('pdo_mysql');
$gdExtension = extension_loaded('gd');
$mbstringExtension = extension_loaded('mbstring');

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step == 2) {
    $dbHost = trim($_POST['db_host'] ?? 'localhost');
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass = $_POST['db_pass'] ?? '';
    $siteUrl = trim($_POST['site_url'] ?? '');
    $adminEmail = trim($_POST['admin_email'] ?? '');
    $adminPassword = $_POST['admin_password'] ?? '';
    
    // Validation
    if (empty($dbName)) $errors[] = 'Database name is required';
    if (empty($dbUser)) $errors[] = 'Database username is required';
    if (empty($siteUrl)) $errors[] = 'Site URL is required';
    if (empty($adminEmail)) $errors[] = 'Admin email is required';
    if (empty($adminPassword) || strlen($adminPassword) < 6) $errors[] = 'Admin password must be at least 6 characters';
    
    if (empty($errors)) {
        // Test database connection
        try {
            $pdo = new PDO("mysql:host=$dbHost;dbname=$dbName;charset=utf8mb4", $dbUser, $dbPass);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        } catch (PDOException $e) {
            $errors[] = 'Database connection failed: ' . $e->getMessage();
        }
    }
    
    if (empty($errors)) {
        // Create config file
        $configContent = "<?php
/**
 * SB Mobile Shop - Configuration File
 * Auto-generated by installer
 */

// Prevent direct access
if (!defined('SB_INSTALL')) {
    die('Direct access not allowed');
}

// Database Configuration
define('DB_HOST', '$dbHost');
define('DB_NAME', '$dbName');
define('DB_USER', '$dbUser');
define('DB_PASS', '$dbPass');
define('DB_CHARSET', 'utf8mb4');

// Site Configuration
define('SITE_NAME', 'SB Mobile Shop');
define('SITE_URL', '$siteUrl');
define('SITE_EMAIL', '$adminEmail');

// Paths
define('ROOT_PATH', dirname(__DIR__) . '/');
define('INCLUDE_PATH', ROOT_PATH . 'includes/');
define('UPLOAD_PATH', ROOT_PATH . 'assets/uploads/');
define('UPLOAD_URL', SITE_URL . '/assets/uploads/');

// Session
define('SESSION_NAME', 'sb_mobile_session');
define('SESSION_LIFETIME', 86400 * 7);

// Pagination
define('ITEMS_PER_PAGE', 12);

// Currency
define('CURRENCY_SYMBOL', '৳');
define('CURRENCY_CODE', 'BDT');

// Timezone
date_default_timezone_set('Asia/Dhaka');

// Error Reporting (Disable in production)
ini_set('display_errors', 0);
error_reporting(0);

// Memory Limit
ini_set('memory_limit', '256M');

// Max Upload Size
define('MAX_UPLOAD_SIZE', 10 * 1024 * 1024);

// Allowed File Types
define('ALLOWED_IMAGE_TYPES', ['image/jpeg', 'image/png', 'image/gif', 'image/webp']);
define('ALLOWED_FILE_TYPES', ['application/pdf', 'application/zip', 'application/x-rar-compressed']);

// Encryption Key
define('ENCRYPTION_KEY', '" . bin2hex(random_bytes(16)) . "');
define('ENCRYPTION_CIPHER', 'AES-256-CBC');

// API Configuration
define('API_ENABLED', true);
define('API_RATE_LIMIT', 100);
";
        
        file_put_contents(__DIR__ . '/includes/config.php', $configContent);
        
        // Create uploads directories
        @mkdir(__DIR__ . '/assets/uploads/products', 0755, true);
        @mkdir(__DIR__ . '/assets/uploads/general', 0755, true);
        
        // Run SQL schema
        $sql = file_get_contents(__DIR__ . '/database/schema.sql');
        
        // Replace placeholder
        $sql = str_replace('`{DB_NAME}`', "`$dbName`", $sql);
        
        // Update admin email and password
        $hashedPassword = password_hash($adminPassword, PASSWORD_DEFAULT);
        $sql = preg_replace(
            "/('admin@sbmobile.shop', ')([^']+)('/, 'Administrator'/",
            "'$adminEmail', '$hashedPassword', 'Administrator'",
            $sql
        );
        
        // Execute SQL
        $statements = explode(';', $sql);
        foreach ($statements as $statement) {
            $statement = trim($statement);
            if (!empty($statement)) {
                try {
                    $pdo->exec($statement);
                } catch (PDOException $e) {
                    // Ignore some errors for idempotent installation
                }
            }
        }
        
        // Create .htaccess for security
        $htaccess = "Options -Indexes
<FilesMatch \"\\.(sql|log|ini|env|htaccess|htpasswd|php|py|pl|sh|cgi)$\">
    Order allow,deny
    Deny from all
</FilesMatch>

# Protect config file
<Files \"config.php\">
    Order allow,deny
    Deny from all
</Files>

# Enable mod_rewrite
RewriteEngine On

# Force HTTPS (optional, uncomment if needed)
# RewriteCond %{HTTPS} off
# RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
";
        
        file_put_contents(__DIR__ . '/.htaccess', $htaccess);
        
        $success = true;
        $step = 3;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SB Mobile Shop - Installation</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
</head>
<body class="bg-gradient-to-br from-blue-900 to-green-600 min-h-screen flex items-center justify-center p-8">
    <div class="bg-white rounded-2xl shadow-2xl max-w-2xl w-full overflow-hidden">
        <!-- Header -->
        <div class="gradient-bg p-8 text-white text-center">
            <div class="w-20 h-20 bg-white/20 rounded-2xl mx-auto mb-4 flex items-center justify-center">
                <i class="fas fa-store text-4xl"></i>
            </div>
            <h1 class="text-3xl font-bold mb-2">SB Mobile Shop</h1>
            <p class="opacity-80">Installation Wizard</p>
        </div>
        
        <!-- Progress -->
        <div class="px-8 pt-6">
            <div class="flex items-center justify-between mb-2">
                <span class="<?php echo $step >= 1 ? 'text-green-600' : 'text-gray-400'; ?>">
                    <i class="fas fa-check-circle<?php echo $step > 1 ? '' : '-o'; ?>"></i> Requirements
                </span>
                <div class="flex-1 h-1 bg-gray-200 mx-4">
                    <div class="h-full bg-green-500 transition-all" style="width: <?php echo ($step - 1) * 50; ?>%"></div>
                </div>
                <span class="<?php echo $step >= 2 ? 'text-green-600' : 'text-gray-400'; ?>">
                    <i class="fas fa-database<?php echo $step > 2 ? '' : '-o'; ?>"></i> Configuration
                </span>
                <div class="flex-1 h-1 bg-gray-200 mx-4">
                    <div class="h-full bg-green-500 transition-all" style="width: <?php echo max(0, ($step - 2)) * 100; ?>%"></div>
                </div>
                <span class="<?php echo $step >= 3 ? 'text-green-600' : 'text-gray-400'; ?>">
                    <i class="fas fa-check<?php echo $step > 3 ? '' : '-o'; ?>"></i> Complete
                </span>
            </div>
        </div>
        
        <!-- Content -->
        <div class="p-8">
            <?php if ($step == 1): ?>
            <!-- Step 1: Requirements -->
            <h2 class="text-xl font-bold mb-6 flex items-center gap-2">
                <i class="fas fa-clipboard-check text-green-600"></i>
                Server Requirements Check
            </h2>
            
            <div class="space-y-4 mb-8">
                <div class="flex items-center justify-between p-4 rounded-lg <?php echo $requirementsMet ? 'bg-green-50' : 'bg-red-50'; ?>">
                    <div>
                        <p class="font-semibold">PHP Version</p>
                        <p class="text-sm text-gray-500">Minimum: 7.4.0</p>
                    </div>
                    <span class="<?php echo $requirementsMet ? 'text-green-600' : 'text-red-600'; ?>">
                        <?php echo $phpVersion; ?> <?php echo $requirementsMet ? '<i class="fas fa-check-circle"></i>' : '<i class="fas fa-times-circle"></i>'; ?>
                    </span>
                </div>
                
                <div class="flex items-center justify-between p-4 rounded-lg <?php echo $pdoExtension ? 'bg-green-50' : 'bg-red-50'; ?>">
                    <div>
                        <p class="font-semibold">PDO MySQL Extension</p>
                        <p class="text-sm text-gray-500">Required for database</p>
                    </div>
                    <span class="<?php echo $pdoExtension ? 'text-green-600' : 'text-red-600'; ?>">
                        <?php echo $pdoExtension ? 'Enabled' : 'Disabled'; ?> <?php echo $pdoExtension ? '<i class="fas fa-check-circle"></i>' : '<i class="fas fa-times-circle"></i>'; ?>
                    </span>
                </div>
                
                <div class="flex items-center justify-between p-4 rounded-lg <?php echo $gdExtension ? 'bg-green-50' : 'bg-yellow-50'; ?>">
                    <div>
                        <p class="font-semibold">GD Extension</p>
                        <p class="text-sm text-gray-500">For image processing</p>
                    </div>
                    <span class="<?php echo $gdExtension ? 'text-green-600' : 'text-yellow-600'; ?>">
                        <?php echo $gdExtension ? 'Enabled' : 'Optional'; ?> <?php echo $gdExtension ? '<i class="fas fa-check-circle"></i>' : '<i class="fas fa-exclamation-circle"></i>'; ?>
                    </span>
                </div>
                
                <div class="flex items-center justify-between p-4 rounded-lg <?php echo $mbstringExtension ? 'bg-green-50' : 'bg-red-50'; ?>">
                    <div>
                        <p class="font-semibold">MBString Extension</p>
                        <p class="text-sm text-gray-500">For text processing</p>
                    </div>
                    <span class="<?php echo $mbstringExtension ? 'text-green-600' : 'text-red-600'; ?>">
                        <?php echo $mbstringExtension ? 'Enabled' : 'Disabled'; ?> <?php echo $mbstringExtension ? '<i class="fas fa-check-circle"></i>' : '<i class="fas fa-times-circle"></i>'; ?>
                    </span>
                </div>
            </div>
            
            <?php if ($requirementsMet && $pdoExtension): ?>
            <a href="?step=2" class="block w-full gradient-bg text-white text-center py-4 rounded-xl font-semibold hover:opacity-90 transition">
                Continue to Configuration <i class="fas fa-arrow-right ml-2"></i>
            </a>
            <?php else: ?>
            <div class="bg-red-50 border border-red-200 text-red-700 p-4 rounded-lg text-center">
                <i class="fas fa-exclamation-triangle mr-2"></i>
                Please enable the required PHP extensions before continuing.
            </div>
            <?php endif; ?>
            
            <?php elseif ($step == 2): ?>
            <!-- Step 2: Configuration -->
            <h2 class="text-xl font-bold mb-6 flex items-center gap-2">
                <i class="fas fa-cog text-green-600"></i>
                Database & Admin Configuration
            </h2>
            
            <?php if (!empty($errors)): ?>
            <div class="bg-red-50 border border-red-200 text-red-700 p-4 rounded-lg mb-6">
                <ul class="list-disc list-inside">
                    <?php foreach ($errors as $e): ?>
                    <li><?php echo escape($e); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php endif; ?>
            
            <form method="POST" class="space-y-6">
                <div class="bg-blue-50 border border-blue-200 p-4 rounded-lg mb-6">
                    <h3 class="font-semibold text-blue-900 mb-2"><i class="fas fa-database mr-2"></i> Database Settings</h3>
                    <p class="text-sm text-blue-700">Get these from your cPanel → MySQL Databases</p>
                </div>
                
                <div class="grid md:grid-cols-2 gap-4">
                    <div>
                        <label class="block text-sm font-medium mb-2">Database Host</label>
                        <input type="text" name="db_host" value="localhost" required
                               class="w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-green-500 outline-none">
                    </div>
                    <div>
                        <label class="block text-sm font-medium mb-2">Database Name</label>
                        <input type="text" name="db_name" required
                               class="w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-green-500 outline-none"
                               placeholder="sb_mobile_shop">
                    </div>
                    <div>
                        <label class="block text-sm font-medium mb-2">Database Username</label>
                        <input type="text" name="db_user" required
                               class="w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-green-500 outline-none">
                    </div>
                    <div>
                        <label class="block text-sm font-medium mb-2">Database Password</label>
                        <input type="password" name="db_pass"
                               class="w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-green-500 outline-none">
                    </div>
                </div>
                
                <div class="bg-green-50 border border-green-200 p-4 rounded-lg mt-6">
                    <h3 class="font-semibold text-green-900 mb-2"><i class="fas fa-globe mr-2"></i> Site Settings</h3>
                </div>
                
                <div>
                    <label class="block text-sm font-medium mb-2">Site URL</label>
                    <input type="url" name="site_url" required
                           value="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . str_replace('/install.php', '', $_SERVER['REQUEST_URI']); ?>"
                           class="w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-green-500 outline-none">
                </div>
                
                <div class="bg-purple-50 border border-purple-200 p-4 rounded-lg mt-6">
                    <h3 class="font-semibold text-purple-900 mb-2"><i class="fas fa-user-shield mr-2"></i> Admin Account</h3>
                    <p class="text-sm text-purple-700">Login credentials for admin panel</p>
                </div>
                
                <div class="grid md:grid-cols-2 gap-4">
                    <div>
                        <label class="block text-sm font-medium mb-2">Admin Email</label>
                        <input type="email" name="admin_email" required
                               class="w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-green-500 outline-none"
                               placeholder="admin@example.com">
                    </div>
                    <div>
                        <label class="block text-sm font-medium mb-2">Admin Password</label>
                        <input type="password" name="admin_password" required minlength="6"
                               class="w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-green-500 outline-none"
                               placeholder="Minimum 6 characters">
                    </div>
                </div>
                
                <div class="flex gap-4 pt-4">
                    <a href="?step=1" class="flex-1 border border-gray-300 text-gray-700 text-center py-4 rounded-xl font-semibold hover:bg-gray-50 transition">
                        <i class="fas fa-arrow-left mr-2"></i> Back
                    </a>
                    <button type="submit" class="flex-1 gradient-bg text-white py-4 rounded-xl font-semibold hover:opacity-90 transition">
                        <i class="fas fa-check mr-2"></i> Install Now
                    </button>
                </div>
            </form>
            
            <?php elseif ($step == 3): ?>
            <!-- Step 3: Complete -->
            <div class="text-center">
                <div class="w-24 h-24 bg-green-100 rounded-full mx-auto mb-6 flex items-center justify-center">
                    <i class="fas fa-check text-green-600 text-5xl"></i>
                </div>
                
                <h2 class="text-2xl font-bold text-gray-900 mb-4">Installation Complete!</h2>
                <p class="text-gray-600 mb-8">
                    SB Mobile Shop has been successfully installed on your server.
                </p>
                
                <div class="bg-gray-50 rounded-xl p-6 mb-8 text-left max-w-md mx-auto">
                    <h3 class="font-semibold mb-4">Next Steps:</h3>
                    <ol class="space-y-3 text-sm">
                        <li class="flex items-start gap-3">
                            <span class="w-6 h-6 bg-green-500 text-white rounded-full flex items-center justify-center text-xs font-bold shrink-0">1</span>
                            <span>Login to admin panel at <code class="bg-white px-2 py-1 rounded">/admin/</code></span>
                        </li>
                        <li class="flex items-start gap-3">
                            <span class="w-6 h-6 bg-green-500 text-white rounded-full flex items-center justify-center text-xs font-bold shrink-0">2</span>
                            <span>Go to Settings and configure your site info</span>
                        </li>
                        <li class="flex items-start gap-3">
                            <span class="w-6 h-6 bg-green-500 text-white rounded-full flex items-center justify-center text-xs font-bold shrink-0">3</span>
                            <span>Add your products and start selling!</span>
                        </li>
                    </ol>
                </div>
                
                <div class="flex flex-col sm:flex-row gap-4 justify-center">
                    <a href="/admin/" class="gradient-bg text-white px-8 py-4 rounded-xl font-semibold hover:opacity-90 transition inline-flex items-center justify-center gap-2">
                        <i class="fas fa-cog"></i> Go to Admin Panel
                    </a>
                    <a href="/" class="border border-gray-300 text-gray-700 px-8 py-4 rounded-xl font-semibold hover:bg-gray-50 transition inline-flex items-center justify-center gap-2">
                        <i class="fas fa-home"></i> View Website
                    </a>
                </div>
                
                <div class="mt-8 pt-8 border-t text-sm text-gray-500">
                    <p class="mb-2"><strong>Important:</strong> Delete the <code>install.php</code> file for security.</p>
                    <p>For support, contact us at support@sbmobile.shop</p>
                </div>
            </div>
            <?php endif; ?>
        </div>
        
        <div class="px-8 py-4 bg-gray-50 text-center text-sm text-gray-500">
            SB Mobile Shop v1.0 - © <?php echo date('Y'); ?> All rights reserved.
        </div>
    </div>
    
    <style>
        .gradient-bg { background: linear-gradient(135deg, hsl(213 50% 23%) 0%, hsl(142 70% 45%) 100%); }
    </style>
</body>
</html>
